services:
  web:
    image: 192.168.99.101:5000/bgapp-web
    deploy:
      endpoint_mode: vip
      mode: global
    ports:
      - target: 80
        published: 8081
        protocol: tcp
        mode: ingress
    volumes:
      - "/home/vagrant/bgapp/web:/var/www/html:ro"
    networks:
      - app-network

  db:
    image: 192.168.99.101:5000/bgapp-db
    deploy:
      endpoint_mode: dnsrr
      mode: global
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password

secrets:
  db_root_password:
    external: true
networks:
  app-network:
